const assert = require("node:assert/strict");
const fs = require("node:fs");

const html = fs.readFileSync("index.html", "utf8");
const css = fs.readFileSync("styles.css", "utf8");
const layout = fs.readFileSync("v22-layout.css", "utf8");
const app = fs.readFileSync("app.js", "utf8");

assert.equal((css.match(/{/g) || []).length, (css.match(/}/g) || []).length, "CSS 大括号应完整闭合");
assert.equal((layout.match(/{/g) || []).length, (layout.match(/}/g) || []).length, "v2.2 布局 CSS 大括号应完整闭合");
assert.match(html, /viewport-fit=cover/, "应适配刘海和底部安全区域");
assert.match(html, /styles\.css\?v=2\.8\.0/, "基础样式应使用 v2.8.0 版本化地址");
assert.match(html, /v22-layout\.css\?v=2\.8\.0/, "规范化移动布局应最后加载");
assert.match(html, /id="mobileMatrixTabs"/, "应提供手机象限切换条");
assert.equal((html.match(/data-mobile-quadrant=/g) || []).length, 4, "应提供四个象限入口");
assert.equal((html.match(/data-mobile-view=/g) || []).length, 5, "底栏应提供今天、优先级、日历、项目和管理员视图映射");
assert.match(html, /data-auth-mode="register"/, "手机登录页应始终提供注册入口");
assert.match(html, /class="auth-gate" id="authGate"/, "登录状态确认前应默认显示隐私遮罩");
assert.match(html, /id="cloudRegisterBtn"/, "云同步登录弹窗也应提供注册入口");
assert.match(html, /id="reminderSettingsBtn"/, "移动侧栏应提供独立提醒设置入口");
assert.match(html, /id="remindersModal"[\s\S]*id="reminderMethodsSection"[\s\S]*id="reminderTestSection"/, "提醒弹窗应包含方式说明和可操作测试");
assert.match(app, /reminderSettingsBtn"\)\.addEventListener\("click", openReminderSettings\)/, "提醒设置按钮必须连接实际弹窗事件");
assert.doesNotMatch(html, /小爱|voiceAssistantSetting|remindersVoice/, "移动界面不应残留已停用的小爱入口");
assert.match(html, /id="connectGoogleBtn"/, "日历同步页应提供 Google 直接双向连接入口");
assert.match(app, /syncGoogleNow/, "Google 日历连接应支持手动双向同步");
assert.match(html, /id="mobileCreateModal"/, "手机添加应使用独立的快速创建面板");
assert.match(html, /id="mobileNavCreate"/, "底栏中央应提供唯一主创建入口");
assert.match(layout, /orientation:landscape/, "应提供手机横屏布局");
assert.match(layout, /body\[data-active-view="schedule"\] \.mobile-bottom-nav \{ display:none/, "横屏课表应隐藏占据高度的底栏");
assert.match(layout, /body\[data-active-view="schedule"\] \.week-deadlines \{ display:none; \}/, "手机竖屏课表应释放固定 DDL 区域的高度");
assert.match(layout, /safe-area-inset-left/, "横屏内容应覆盖并适配左右安全区域");
assert.match(layout, /grid-template-columns:calc\(64px \+ var\(--safe-left\)\) minmax\(0,1fr\)/, "非课表横屏应使用带安全区的左侧导航轨而不是底部横栏");
assert.match(layout, /--safe-left:max\(env\(safe-area-inset-left\),var\(--native-safe-left,0px\)\)/, "安全区应兼容浏览器与 Android 原生 Insets，不得丢失刘海避让");
assert.match(layout, /grid-template-rows:repeat\(5,56px\)/, "横屏导航轨应保持紧凑触控尺寸");
assert.match(layout, /\.sidebar-actions #cloudBtn \{ grid-column:1 \/ -1; \}/, "手机备份区应使用整齐的两列按钮网格");
assert.match(html, /data-schedule-mode="timetable"/, "日历应把通用周视图与教学课表分开");
assert.match(layout, /body\[data-active-view="matrix"\] \.matrix-board/, "横屏四象限应使用视图级隔离规则");
assert.match(layout, /contain:strict/, "横屏四象限应阻止内容撑破网格");
assert.match(layout, /max-height:43px/, "横屏任务卡应限制高度并在象限内部滚动");
assert.match(html, /class="icon-sprite"/, "主要导航应使用统一的线性 SVG 图标");
assert.match(html, /data-landscape-schedule-action="import"/, "沉浸课表仍应提供导入和设置入口");
assert.match(layout, /grid-template-columns:1fr 1fr/, "横屏应恢复二乘二象限");
assert.match(layout, /env\(safe-area-inset-bottom\)/, "固定控件应避开系统手势区");
assert.match(css, /\.month-weekdays,\.month-grid \{ min-width:0/, "手机月历应在整屏内显示");
assert.match(app, /function selectMobileQuadrant/, "应实现象限点击切换");
assert.match(app, /mobileLayout \? "day" : "month"/, "手机首次进入日历应默认日视图");
assert.match(app, /if \(activeView === "schedule"\) renderSchedule\(\)/, "非日历操作不应反复重建整套日历");
assert.match(app, /if \(enteringSchedule\) renderAll\(\)/, "重新进入日历时应刷新延迟渲染的内容");
assert.match(app, /data-mobile-view/, "手机底部导航应连接实际视图");
assert.match(app, /resetAdminUserPassword/, "管理员应能恢复无法登录的普通账号");
assert.match(app, /beforeinstallprompt/, "应支持安装为无地址栏的桌面应用");
assert.match(css, /\.quick-add \{ display:none !important;/, "手机不应常驻显示遮挡内容的输入框");
assert.match(layout, /grid-template-rows:minmax\(0,1fr\) auto/, "移动端应由内容区和底栏组成稳定 App Shell");
assert.match(layout, /\.quadrant\.mobile-active \{ display:flex; \}/, "竖屏只显示当前选中象限列表");
assert.match(layout, /position:static !important/, "手机底部导航应参与布局而不是覆盖内容");
assert.match(layout, /\.complete-btn,.focus-task \.complete-btn,.list-row \.complete-btn \{ width:34px; height:34px; min-width:34px; min-height:34px; aspect-ratio:1/, "完成按钮必须保持正圆而不是被全局触控高度拉成椭圆");
assert.match(html, /id="sidebarBackdrop"/, "移动侧栏必须有独立遮罩和关闭区域");
assert.match(layout, /\.sidebar\.open \+ \.sidebar-backdrop/, "打开侧栏时必须隔离正文和底部导航");
assert.match(app, /mobileNavCreate.*openPrimaryCreate/, "底栏主按钮应可靠打开快速创建面板");
assert.doesNotMatch(html, /id="mobileCreateFab"/, "不应保留第二个悬浮创建入口");

console.log("手机端检查通过：100dvh App Shell、竖屏象限总览、横屏四象限、唯一创建入口和安全区域均已覆盖。");
